apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-nginx-loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab4-nginx-loadbalancer
  template:
    metadata:
      labels:
        app: lab4-nginx-loadbalancer
    spec:
      containers:
      - name: lab4-nginx
        image: lab4-nginx:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lab4-nginx-loadbalancer-service
spec:
  type: LoadBalancer 
  selector:
    app: lab4-nginx-loadbalancer
  ports:
  - port: 80 # cổng service trong cluster
    targetPort: 80 # cổng trong container