apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab4-nginx
  template:
    metadata:
      labels:
        app: lab4-nginx
    spec:
      containers:
      - name: lab4-nginx
        image: lab4-nginx:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lab4-nginx-nodeport
spec:
  type: NodePort
  selector:
    app: lab4-nginx
  ports:
  - port: 80 # cổng service trong cluster
    targetPort: 80 # cổng trong container
    nodePort: 31000 # cổng mở ra node
